version: '3.9'
services:
  bff-band-web:
    container_name: bff_band_web
    image: node:hydrogen-alpine
    command: sh -c "cd /app && node dist/main"
    #command: tail -F anything
    ports:
      - 3001:3000
    networks:
      - net-db
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - ./views:/app/views
      - ./.prod.env:/app/.env
    restart: unless-stopped

networks:
  net-db:
    name: net-db
    driver: bridge